version: "3.7"

services:
  runner:
    image: myoung34/github-runner:latest
    environment:
      REPO_URL: "https://github.com/thebino/esp_iot_template"
      RUNNER_NAME: "esp-runer"
      RUNNER_LABELS: "esp32"
      RUNNER_TOKEN: "RUNNER_TOKEN "
      RUNNER_WORKDIR: /tmp/runner/work
      RUNNER_SCOPE: 'repo'
      LABELS: linux,x64,gpu
    volumes:
      - /tmp/runner:/tmp/runner
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev/:/dev/
