/**
 * File:     bluetooth_gatt.h
 *
 * Author:   Stürmer Benjamin (webmaster@stuermer-benjamin.de)
 * Date:     Spring 2022
 *
 * Summary of File:
 *
 *   This file contains code to define the BLE services (Attribute Protocol)
 *   and comes into action after the advertisement and connection phase
 *   governed by GAP has finished and a connection has established.
 */
#ifndef BLUETOOTH_GATT_H
#define BLUETOOTH_GATT_H

#pragma once

#include "host/ble_hs.h"
#include "host/ble_uuid.h"
#include "services/gap/ble_svc_gap.h"
#include "services/gatt/ble_svc_gatt.h"

/**
 * UUIDs for custom services and characteristics
 * 
 * These uuids can be generated by any online tool
 * while not colliding with the Bluetooth SIG base UUID
 * 
 * xxxxxxxx-0000-1000-8000-00805F9B34FB
 * 
 * all uuids are in little-endian  (right-to-left <-)
 */

// service: OTA Service
// 00000010-1000-2000-3000-111122223333
static const ble_uuid128_t s_gatt_service_uuid_ota = BLE_UUID128_INIT(
    0x33, 0x33, 0x22, 0x22, 
    0x11, 0x11, 0x00, 0x30,
    0x00, 0x20, 0x00, 0x10, 
    0x10, 0x00, 0x00, 0x00);

// characteristic: OTA Control
// 00000011-1000-2000-3000-111122223333
static const ble_uuid128_t s_gatt_svr_chr_ota_control_uuid = BLE_UUID128_INIT(
    0x33, 0x33, 0x22, 0x22, 
    0x11, 0x11, 0x00, 0x30,
    0x00, 0x20, 0x00, 0x10, 
    0x11, 0x00, 0x00, 0x00);

// characteristic: OTA Data
// 00000012-1000-2000-3000-111122223333
static const ble_uuid128_t s_gatt_svr_chr_ota_data_uuid = BLE_UUID128_INIT(
    0x33, 0x33, 0x22, 0x22, 
    0x11, 0x11, 0x00, 0x30,
    0x00, 0x20, 0x00, 0x10, 
    0x12, 0x00, 0x00, 0x00);

// service: Control Service
// 00000020-1000-2000-3000-111122223333
static const ble_uuid128_t s_gatt_service_uuid_control = BLE_UUID128_INIT(
    0x33, 0x33, 0x22, 0x22, 
    0x11, 0x11, 0x00, 0x30,
    0x00, 0x20, 0x00, 0x10, 
    0x20, 0x00, 0x00, 0x00);

// characteristic: Control Read
// 00000021-1000-2000-3000-111122223333
static const ble_uuid128_t s_gatt_svr_chr_control_read_uuid = BLE_UUID128_INIT(
    0x33, 0x33, 0x22, 0x22, 
    0x11, 0x11, 0x00, 0x30,
    0x00, 0x20, 0x00, 0x10, 
    0x21, 0x00, 0x00, 0x00);

// characteristic: Control Write
// 00000022-1000-2000-3000-111122223333
static const ble_uuid128_t s_gatt_svr_chr_control_write_uuid = BLE_UUID128_INIT(
    0x33, 0x33, 0x22, 0x22, 
    0x11, 0x11, 0x00, 0x30,
    0x00, 0x20, 0x00, 0x10, 
    0x22, 0x00, 0x00, 0x00);

#endif /* BLUETOOTH_GATT_H */
